# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
from recommonmark.parser import CommonMarkParser
#sys.path.insert(0, os.path.abspath('C:/Users/hhz/Anaconda3/Lib/site-packages/zoopt'))
#sys.path.insert(0, os.path.abspath('C:/Users/hhz/Anaconda3/Lib/site-packages/zoopt/utils'))
#sys.path.insert(0, os.path.abspath('C:/Users/hhz/Anaconda3/Lib/site-packages/zoopt/algos/opt_algorithms/paretoopt'))
#sys.path.insert(0, os.path.abspath('C:/Users/hhz/Anaconda3/Lib/site-packages/zoopt/algos/opt_algorithms/racos'))
#sys.path.insert(0, os.path.abspath('C:/Users/hhz/Anaconda3/Lib/site-packages/zoopt/algos/noise_handling'))
#sys.path.insert(0, os.path.abspath('C:/Users/hhz/Anaconda3/Lib/site-packages/zoopt/algos/high_dimensionality_handling'))
#sys.path.insert(0, os.path.abspath('C:/Users/hhz/Anaconda3/Lib/site-packages/zoopt/algos/racos'))
# sys.path.insert(0, os.path.abspath('../../example'))
#sys.path.insert(0, os.path.abspath('D:/ZOOpt/ZOOpt-0.2.1/example/direct_policy_search_for_gym'))
#sys.path.insert(0, os.path.abspath('D:/ZOOpt/ZOOpt-0.2.1/example/linear_classifier_using_ramploss'))
#sys.path.insert(0, os.path.abspath('D:/ZOOpt/ZOOpt-0.2.1/example/sequential_random_embedding'))
#sys.path.insert(0, os.path.abspath('D:/ZOOpt/ZOOpt-0.2.1/example/simple_functions'))
#sys.path.insert(0, os.path.abspath('D:/ZOOpt/ZOOpt-0.2.1/example/sparse_regression'))
#sys.path.insert(0, os.path.abspath('../../../../'))
sys.path.insert(0, os.path.abspath('../zoopt'))
sys.path.insert(0, os.path.abspath('../zoopt/utils'))
sys.path.insert(0, os.path.abspath('../zoopt/algos/opt_algorithms/paretoopt'))
sys.path.insert(0, os.path.abspath('../zoopt/algos/opt_algorithms/racos'))
sys.path.insert(0, os.path.abspath('../zoopt/algos/noise_handling'))
sys.path.insert(0, os.path.abspath('../zoopt/algos/high_dimensionality_handling'))
sys.path.insert(0, os.path.abspath('../zoopt/algos/racos'))
# sys.path.insert(0, os.path.abspath('../../example'))
sys.path.insert(0, os.path.abspath('../example/direct_policy_search_for_gym'))
sys.path.insert(0, os.path.abspath('../example/linear_classifier_using_ramploss'))
sys.path.insert(0, os.path.abspath('../example/sequential_random_embedding'))
sys.path.insert(0, os.path.abspath('../example/simple_functions'))
sys.path.insert(0, os.path.abspath('../example/sparse_regression'))
sys.path.insert(0, os.path.abspath('../'))

# -- Project information -----------------------------------------------------

project = 'ZOOpt'
copyright = u'2018, Yu-Ren Liu, Xiong-Hui Chen, Yi-Qi Hu, Han-Zhe Hu, Yang Yu'
author = u'Yu-Ren Liu, Xiong-Hui Chen, Yi-Qi Hu, Yang Yu'

# The short X.Y version
version = u'0.2.1'
# The full version, including alpha/beta/rc tags
release = u'0.2.1'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.viewcode',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_parsers = {
    '.md': CommonMarkParser,
}
source_suffix = ['.rst', '.md']
#source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'collapse_navigation': False,
    'sticky_navigation': False,
    'navigation_depth': 4,
    'display_version': True
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ZOOptdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ZOOpt.tex', 'ZOOpt Documentation',
     u'Yu-Ren Liu, Xiong-Hui Chen, Yi-Qi Hu, Han-Zhe Hu, Yang Yu', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'zoopt', 'ZOOpt Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ZOOpt', 'ZOOpt Documentation',
     author, 'ZOOpt', 'One line description of project.',
     'Miscellaneous'),
]
def skip(app, what, name, obj, skip, options):
    if name == "__init__":
        return False
    return skip

def setup(app):
    app.connect("autodoc-skip-member", skip)
